# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:

# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# https://docs.microsoft.com/azure/devops/pipelines/languages/android
# https://docs.microsoft.com/en-au/azure/devops/pipelines/?view=azure-devops

# Triggers
trigger:
  batch: true
  branches:
    include:
      - '*'

# Load Variables
variables:
  - template: build-variables.yml

# Define Stages & Jobs
stages:
  - stage: Pre
    jobs:
      - job: GradleClean
        pool:
          vmImage: ${{ variables.VM_IMAGE }}
        steps:
          - task: Gradle@2
            inputs:
              gradleWrapperFile: ${{ variables.GRADLE_WRAPPER_FILE }}
              gradleOptions: ${{ variables.GRADLE_OPTIONS }}
              tasks: 'clean'

  - stage: Build
    jobs:
      - job: GradleAssemble
        pool:
          vmImage: ${{ variables.VM_IMAGE }}
        steps:
          - task: Gradle@2
            enabled: true
            inputs:
              gradleWrapperFile: ${{ variables.GRADLE_WRAPPER_FILE }}
              gradleOptions: ${{ variables.GRADLE_OPTIONS }}
              tasks: 'assemble'

  - stage: Lint
    jobs:
      - job: GradleLint
        pool:
          vmImage: ${{ variables.VM_IMAGE }}
        steps:
          - task: Gradle@2
            enabled: true
            inputs:
              gradleWrapperFile: ${{ variables.GRADLE_WRAPPER_FILE }}
              gradleOptions: ${{ variables.GRADLE_OPTIONS }}
              checkStyleRunAnalysis: true
              findBugsRunAnalysis: true
              pmdRunAnalysis: true
              tasks: 'lint'

  - stage: Test
    jobs:
      - job: GradleTest
        pool:
          vmImage: ${{ variables.VM_IMAGE }}
        steps:
          - task: Gradle@2
            inputs:
              gradleWrapperFile: ${{ variables.GRADLE_WRAPPER_FILE }}
              gradleOptions: ${{ variables.GRADLE_OPTIONS }}
              publishJUnitResults: true
              tasks: 'test'

